
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class AudioConfig : BeanBase
    {
        public AudioConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Desc = _buf.ReadString();
            AssetName = _buf.ReadString();

            PostInit();
        }

        public static AudioConfig DeserializeAudioConfig(ByteBuf _buf)
        {
            return new AudioConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string Desc;

        /// <summary>
        /// 描述
        /// </summary>
        public readonly string AssetName;


        public const int __ID__ = 1647377048;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Desc:" + Desc + ","
            + "AssetName:" + AssetName + ","
            + "}";
        }

        partial void PostInit();
    }
}
