
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ColliderConfig : BeanBase
    {
        public ColliderConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ColliderParams = ColliderParams.DeserializeColliderParams(_buf);

            PostInit();
        }

        public static ColliderConfig DeserializeColliderConfig(ByteBuf _buf)
        {
            return new ColliderConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 碰撞体参数
        /// </summary>
        public readonly ColliderParams ColliderParams;


        public const int __ID__ = -1222308746;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            ColliderParams?.ResolveRef();
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ColliderParams:" + ColliderParams + ","
            + "}";
        }

        partial void PostInit();
    }
}
