//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;


namespace ET
{

public sealed partial class ColliderConfig: Bright.Config.BeanBase
{
    public ColliderConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ColliderType = (EColliderType)_buf.ReadInt();
        Desc = _buf.ReadString();
        IsSensor = _buf.ReadBool();
        Offset = _buf.ReadVector2();
        Radius = _buf.ReadFloat();
        HX = _buf.ReadFloat();
        HY = _buf.ReadFloat();
        Angle = _buf.ReadFloat();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Points = new System.Collections.Generic.List<System.Numerics.Vector2>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { System.Numerics.Vector2 _e0;  _e0 = _buf.ReadVector2(); Points.Add(_e0);}}
        PointCount = _buf.ReadInt();
        PostInit();
    }

    public static ColliderConfig DeserializeColliderConfig(ByteBuf _buf)
    {
        return new ColliderConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 碰撞体类型类型
    /// </summary>
    public EColliderType ColliderType { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }
    /// <summary>
    /// 是否为触发器
    /// </summary>
    public bool IsSensor { get; private set; }
    /// <summary>
    /// 偏移
    /// </summary>
    public System.Numerics.Vector2 Offset { get; private set; }
    /// <summary>
    /// 半径
    /// </summary>
    public float Radius { get; private set; }
    /// <summary>
    /// x轴方向上的一半长度
    /// </summary>
    public float HX { get; private set; }
    /// <summary>
    /// Y轴方向上的一半长度
    /// </summary>
    public float HY { get; private set; }
    /// <summary>
    /// 旋转角度
    /// </summary>
    public float Angle { get; private set; }
    /// <summary>
    /// 碰撞体所包含的顶点信息(顺时针),可能由多个多边形组成
    /// </summary>
    public System.Collections.Generic.List<System.Numerics.Vector2> Points { get; private set; }
    /// <summary>
    /// 总顶点数
    /// </summary>
    public int PointCount { get; private set; }

    public const int __ID__ = -1222308746;
    public override int GetTypeId() => __ID__;

    public  void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ColliderType:" + ColliderType + ","
        + "Desc:" + Desc + ","
        + "IsSensor:" + IsSensor + ","
        + "Offset:" + Offset + ","
        + "Radius:" + Radius + ","
        + "HX:" + HX + ","
        + "HY:" + HY + ","
        + "Angle:" + Angle + ","
        + "Points:" + Bright.Common.StringUtil.CollectionToString(Points) + ","
        + "PointCount:" + PointCount + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}