
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public abstract partial class ColliderParams : BeanBase
    {
        public ColliderParams(ByteBuf _buf)
        {

            PostInit();
        }

        public static ColliderParams DeserializeColliderParams(ByteBuf _buf)
        {
            switch (_buf.ReadInt())
            {
                case CircleColliderParams.__ID__: return new CircleColliderParams(_buf);
                case BoxColliderParams.__ID__: return new BoxColliderParams(_buf);
                case PolygonColliderParams.__ID__: return new PolygonColliderParams(_buf);
                default: throw new SerializationException();
            }
        }



        public virtual void ResolveRef()
        {
        }

        public override string ToString()
        {
            return "{ "
            + "}";
        }

        partial void PostInit();
    }
}
