
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using System.Collections.Generic;

namespace ET
{
    [Config]
    public partial class AreaConfigCategory : Singleton<AreaConfigCategory>, IConfig
    {
        private readonly Dictionary<int, AreaConfig> _dataMap;
        private readonly List<AreaConfig> _dataList;

        public AreaConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, AreaConfig>();
            _dataList = new List<AreaConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AreaConfig _v;
                _v = AreaConfig.DeserializeAreaConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, AreaConfig> DataMap => _dataMap;
        public List<AreaConfig> DataList => _dataList;

        public AreaConfig GetOrDefault(int key) => _dataMap.GetValueOrDefault(key);
        public AreaConfig Get(int key)
        {
            if (_dataMap.TryGetValue(key,out var v))
            {
                return v;
            }
            ConfigLog.Error(this,key);
            return null;
        }

        public void ResolveRef()
        {
            foreach(var _v in _dataList)
            {
                _v.ResolveRef();
            }
        }

        partial void PostInit();
    }
}
