
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban;

namespace ET
{
    [Config]
    public partial class AudioConfigCategory : Singleton<AudioConfigCategory>
    {
        private readonly Dictionary<int, AudioConfig> _dataMap;
        private readonly List<AudioConfig> _dataList;

        public AudioConfigCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<int, AudioConfig>();
            _dataList = new List<AudioConfig>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                AudioConfig _v;
                _v = AudioConfig.DeserializeAudioConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }

            PostInit();
        }

        public Dictionary<int, AudioConfig> DataMap => _dataMap;
        public List<AudioConfig> DataList => _dataList;

        public AudioConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public AudioConfig Get(int key) => _dataMap[key];
        public AudioConfig this[int key] => _dataMap[key];

        partial void PostInit();
    }
}
