
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using Luban;

namespace ET
{
    [Config]
    public partial class LocalizeConfig_UI_CHSCategory : Singleton<LocalizeConfig_UI_CHSCategory>
    {
        private readonly Dictionary<string, LocalizeConfig_CHS> _dataMap;
        private readonly List<LocalizeConfig_CHS> _dataList;

        public LocalizeConfig_UI_CHSCategory(ByteBuf _buf)
        {
            _dataMap = new Dictionary<string, LocalizeConfig_CHS>();
            _dataList = new List<LocalizeConfig_CHS>();

            for (int n = _buf.ReadSize(); n > 0; --n)
            {
                LocalizeConfig_CHS _v;
                _v = LocalizeConfig_CHS.DeserializeLocalizeConfig_CHS(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Key, _v);
            }

            PostInit();
        }

        public Dictionary<string, LocalizeConfig_CHS> DataMap => _dataMap;
        public List<LocalizeConfig_CHS> DataList => _dataList;

        public LocalizeConfig_CHS GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public LocalizeConfig_CHS Get(string key) => _dataMap[key];
        public LocalizeConfig_CHS this[string key] => _dataMap[key];

        partial void PostInit();
    }
}
