
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class SectorColliderParams : ColliderParams
    {
        public SectorColliderParams(ByteBuf _buf) : base(_buf) 
        {
            Radius = _buf.ReadFloat();
            Angle = _buf.ReadFloat();

            PostInit();
        }

        public static SectorColliderParams DeserializeSectorColliderParams(ByteBuf _buf)
        {
            return new SectorColliderParams(_buf);
        }

        public readonly float Radius;

        public readonly float Angle;


        public const int __ID__ = 1838752704;
        public override int GetTypeId() => __ID__;

        public override void ResolveRef()
        {
            base.ResolveRef();
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Radius:" + Radius + ","
            + "Angle:" + Angle + ","
            + "}";
        }

        partial void PostInit();
    }
}
