
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class ServerInfoConfig : BeanBase
    {
        public ServerInfoConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            ServerName = _buf.ReadString();

            PostInit();
        }

        public static ServerInfoConfig DeserializeServerInfoConfig(ByteBuf _buf)
        {
            return new ServerInfoConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 服务器名
        /// </summary>
        public readonly string ServerName;

        public const int __ID__ = -1669631661;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ServerName:" + ServerName + ","
            + "}";
        }

        partial void PostInit();
    }
}
