//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System;

namespace ET
{
   
[Config]
public partial class AudioConfigCategory: ConfigSingleton<AudioConfigCategory>
{
    private readonly Dictionary<int, AudioConfig> _dataMap;
    private readonly List<AudioConfig> _dataList;
    
    public AudioConfigCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, AudioConfig>();
        _dataList = new List<AudioConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            AudioConfig _v;
            _v = AudioConfig.DeserializeAudioConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, AudioConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<AudioConfig> DataList => _dataList;

    public AudioConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AudioConfig Get(int key) => _dataMap[key];
    public AudioConfig this[int key] => _dataMap[key];

    public override void Resolve(ConcurrentDictionary<Type, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(AudioConfig).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}