//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum ESkillIndicatorType
    {
        CommonAttack = 1,
        Position = 2,
        Line = 3,
        Angle = 4,
        TargetOnly = 5,
    }

} 
