
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class LocalizeConfig_CHT : ALocalizeConfig
    {
        public LocalizeConfig_CHT(ByteBuf _buf) : base(_buf) 
        {
            TextCHT = _buf.ReadString();

            PostInit();
        }

        public static LocalizeConfig_CHT DeserializeLocalizeConfig_CHT(ByteBuf _buf)
        {
            return new LocalizeConfig_CHT(_buf);
        }

        public readonly string TextCHT;

        public const int __ID__ = -887446245;

        public override int GetTypeId() => __ID__;

        public override string ToString()
        {
            return "{ "
            + "key:" + Key + ","
            + "TextCHT:" + TextCHT + ","
            + "}";
        }

        partial void PostInit();
    }
}
