
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace ET
{
    [EnableClass]
    public sealed partial class MapConfig : BeanBase
    {
        public MapConfig(ByteBuf _buf)
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            AssetPath = _buf.ReadString();
            PlayerSpawnPoint = ExternalTypeUtil.NewVector3(vector3.Deserializevector3(_buf));
            {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);AreaConfigIds = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); AreaConfigIds.Add(_e0);}}

            PostInit();
        }

        public static MapConfig DeserializeMapConfig(ByteBuf _buf)
        {
            return new MapConfig(_buf);
        }

        /// <summary>
        /// Id
        /// </summary>
        public readonly int Id;

        /// <summary>
        /// 地图名称
        /// </summary>
        public readonly string Name;

        /// <summary>
        /// 资源路径
        /// </summary>
        public readonly string AssetPath;

        /// <summary>
        /// 玩家出生点
        /// </summary>
        public readonly System.Numerics.Vector3 PlayerSpawnPoint;

        /// <summary>
        /// 特殊区域
        /// </summary>
        public readonly System.Collections.Generic.List<int> AreaConfigIds;


        public const int __ID__ = -1840922722;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef()
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "AssetPath:" + AssetPath + ","
            + "PlayerSpawnPoint:" + PlayerSpawnPoint + ","
            + "AreaConfigIds:" + Luban.StringUtil.CollectionToString(AreaConfigIds) + ","
            + "}";
        }

        partial void PostInit();
    }
}
