
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum SkillIndicatorType
    {
        /// <summary>
        /// 单一目标指示器
        /// </summary>
        TargetOnly = 1,

        /// <summary>
        /// 圆形指示器
        /// </summary>
        Circle = 2,

        /// <summary>
        /// 扇形指示器
        /// </summary>
        Umbrella = 3,

        /// <summary>
        /// 范围指示器
        /// </summary>
        Range = 4,

        /// <summary>
        /// 单线指示器
        /// </summary>
        SingleLine = 5,

    }
}
