
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UnitPosType
    {
        /// <summary>
        /// 头顶
        /// </summary>
        Head = 0,

        /// <summary>
        /// 正中央
        /// </summary>
        Center = 1,

        /// <summary>
        /// 底部
        /// </summary>
        Ground = 2,

        /// <summary>
        /// 正前方
        /// </summary>
        Front = 3,

        /// <summary>
        /// 左手
        /// </summary>
        LeftHand = 4,

        /// <summary>
        /// 右手
        /// </summary>
        RightHand = 5,

        /// <summary>
        /// 武器前端
        /// </summary>
        WeaponStart = 6,

        /// <summary>
        /// 武器中间
        /// </summary>
        WeaponCenter = 7,

        /// <summary>
        /// 武器末端
        /// </summary>
        WeaponEnd = 8,

    }
}
