
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ET
{
    public enum UnitType
    {
        Invalid = 0,

        Player = 1,

        Monster = 2,

        NPC = 3,

        Item = 4,

        Skill = 5,

        Area = 6,

    }
}
